class_names = {
    "person" : ["person","individual", "human", "man", "guy", "gentelman", "woman", "boy", "girl", "dad", "father", "mother", "daddy", "policeman", "prisoner", "guy", "men", "character", "people", "gay", "lesbain"],
    "bicycle" : ["bicycle","bike"],
    "car" : ["car","automobile", "vehicle", "vehicle", "truck", "passenger car", "buggy", "chariot", "sedan", "taxi"],
    "motorbike" : ["motorbike","moped", "scooter", "motor scooter", "motorcycle"],
    "aeroplane" : ["aeroplane","airplane", "jet", "flying machine", "airship"],
    "bus" : ["bus","taxi"],
    "train" : ["train","locomotive", "railroad"],
    "truck" : ["truck","transporter", "dump truck"],
    "boat": ["boat", "ship", "vessel", "craft", "watercraft"],
    "traffic light": ["traffic light", "signal", "stoplight", "semaphore", "stop signal"],
    "fire hydrant": ["fire hydrant", "hydrant", "fireplug", "water plug", "fire valve"],
    "stop sign": ["stop sign", "stop signal", "stop board", "halt sign", "intersection sign"],
    "parking meter": ["parking meter", "parking ticket machine", "pay-and-display machine", "coin-operated meter", "parking payment device"],
    "bench": ["bench", "seat", "stool", "perch", "sitting furniture"],
    "bird": ["bird", "avian", "feathered creature", "fowl", "winged animal"],
    "cat": ["cat", "feline", "kitty", "kitten", "pussycat"],
    "dog": ["dog", "canine", "puppy", "pooch", "hound"],
    "horse": ["horse", "equine", "stallion", "steed", "pony"],
    "sheep": ["sheep", "ewe", "lamb", "ram", "flock"],
    "cow": ["cow", "bovine", "bull", "dairy animal"],
    "elephant": ["elephant", "pachyderm", "jumbo", "tusker", "mammoth"],
    "bear": ["bear", "ursine", "grizzly", "polar bear", "bruin"],
    "zebra": ["zebra", "striped horse", "equine", "wild horse", "safari animal"],
    "giraffe": ["giraffe", "tall mammal", "long-necked creature", "safari animal", "towering ungulate"],
    "backpack": ["backpack", "knapsack", "rucksack", "pack", "bag"],
    "umbrella": ["umbrella", "parasol", "canopy", "rain shade", "sunshade"],
    "handbag": ["handbag", "purse", "pocketbook", "clutch", "shoulder bag"],
    "tie": ["tie", "necktie", "cravat", "neckwear", "neckcloth"],
    "suitcase": ["suitcase", "luggage", "travel bag", "portmanteau", "carry-on"],
    "frisbee": ["frisbee", "flying disc", "disc", "flying saucer", "throwing toy"],
    "skis": ["skis", "ski boards", "snow skates", "snow sliders", "winter equipment"],
    "snowboard": ["snowboard", "snowboarder", "boarding equipment", "snow slider", "winter board"],
    "sports ball": ["sports ball", "athletic ball", "play ball", "sporting sphere", "game ball"],
    "kite": ["kite", "flying toy", "wind toy", "aerial device", "airborne plaything"],
    "baseball bat": ["baseball bat", "bat", "club", "hitting stick", "slugger"],
    "baseball glove": ["baseball glove", "catcher's mitt", "fielding glove", "handwear", "ball glove"],
    "skateboard": ["skateboard", "skater board", "riding device", "rolling deck", "street sport equipment"],
    "surfboard": ["surfboard", "surfing board", "wave rider", "water sport equipment", "aquatic board"],
    "tennis racket": ["tennis racket", "racket", "racquet", "paddle", "striking tool"],
    "bottle": ["bottle", "container", "vessel", "flask", "jar"],
    "wine glass": ["wine glass", "glassware", "stemware", "drinking vessel", "wine goblet"],
    "cup": ["cup", "mug", "beverage container", "drinking cup", "teacup"],
    "fork": ["fork", "utensil", "eating tool", "tableware", "dining fork"],
    "knife": ["knife", "blade", "cutlery", "eating tool", "sharp edge"],
    "spoon": ["spoon", "utensil", "eating tool", "tableware", "scooping spoon"],
    "bowl": ["bowl", "dish", "vessel", "container", "deep dish"],
    "banana": ["banana", "yellow fruit", "tropical fruit", "plantain"],
    "apple": ["apple", "red fruit", "crunchy fruit", "pomaceous fruit"],
    "sandwich": ["sandwich", "burger", "sub", "hoagie", "filled roll"],
    "orange": ["orange", "citrus fruit", "tangerine", "mandarin", "citrus"],
    "broccoli": ["broccoli", "vegetable", "green vegetable", "cruciferous vegetable", "broccolini"],
    "carrot": ["carrot", "vegetable", "orange vegetable", "root vegetable", "carotene"],
    "hot dog": ["hot dog", "frankfurter", "sausage", "wiener", "bun"],
    "pizza": ["pizza", "slice", "cheesy pie", "Italian pie", "pizza pie"],
    "donut": ["donut", "doughnut", "sweet pastry", "fried ring", "torus"],
    "cake": ["cake", "pastry", "baked dessert", "layered cake", "celebration cake"],
    "chair": ["chair", "seat", "furniture", "stool", "sitting device"],
    "sofa": ["sofa", "couch", "settee", "lounge", "comfortable seat"],
    "pottedplant": ["potted plant", "plant", "pot plant", "indoor plant", "container plant"],
    "bed": ["bed", "sleeping furniture", "mattress", "bedstead", "sleeping surface"],
    "diningtable": ["dining table", "table", "eating surface", "dining furniture", "meal table"],
    "toilet": ["toilet", "bathroom fixture", "commode", "restroom appliance", "water closet"],
    "tvmonitor": ["TV monitor", "television", "screen", "monitor", "display"],
    "laptop": ["laptop", "notebook computer", "portable computer", "laptop computer", "mobile PC"],
    "mouse": ["mouse", "computer mouse", "input device", "pointing device", "cursor controller"],
    "remote": ["remote", "remote control", "controller", "clicker", "wireless device"],
    "keyboard": ["keyboard", "typing device", "input device", "keypad", "typing board"],
    "cell phone": ["cell phone", "mobile phone", "smartphone", "cellular device", "handheld phone"],
    "microwave": ["microwave", "microwave oven", "oven", "cooking appliance", "heating device"],
    "oven": ["oven", "cooking appliance", "baking oven", "heating device", "stove"],
    "toaster": ["toaster", "toasting appliance", "bread toaster", "toasting device", "toaster oven"],
    "sink": ["sink", "kitchen sink", "basin", "washbasin", "water basin"],
    "refrigerator": ["refrigerator", "fridge", "cooling appliance", "chiller", "icebox"],
    "book": ["book", "volume", "publication", "reading material", "printed work"],
    "clock": ["clock", "timepiece", "timekeeper", "watch", "chronometer"],
    "vase": ["vase", "flower holder", "decorative container", "flower pot", "ornamental vase"],
    "scissors": ["scissors", "cutting tool", "shears", "clippers", "snippers"],
    "teddy bear": ["teddy bear", "stuffed toy", "plushie", "cuddly bear", "soft toy"],
    "hair drier": ["hair drier", "hair dryer", "blow dryer", "hair blower", "drying device"],
    "toothbrush": ["toothbrush", "dental brush", "teeth cleaner", "oral care tool", "tooth cleaner"]
}
